# Text Representation 

In [1]:
# 1. Bag of words 
# we are use countvectorization 

In [9]:
import numpy as np 
import pandas as pd 

In [10]:
df = pd.DataFrame({'text':['people watch cricket' , 'player was player' , 
                           'people write comment' ,
                           'cricket play comment' ] , 'output':[1,1,0,0]})

df

text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [11]:
from sklearn.feature_extraction.text import CountVectorizer 

In [12]:
cv = CountVectorizer() 

In [14]:
bow = cv.fit_transform(df['text'])

In [8]:
# vocab 
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}


In [9]:
print(bow[0].toarray()) 
print(bow[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]


In [10]:
cv.transform(["cricket watch and write comment of cricket comment"]).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]], dtype=int64)

In [11]:
# 2.N-grams

In [12]:
# cv = CountVectorizer(ngram_range(2,2))

In [24]:
v = CountVectorizer(ngram_range=(1, 2))

# v = CountVectorizer(ngram_range=(2, 2))

In [25]:
bow =  v.fit_transform(df['text'])

In [27]:
df['text']

0    people watch cricket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [26]:
# vocab
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 4, 'watch cricket': 13, 'player': 8, 'was': 10, 'player was': 9, 'was player': 11, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}


In [16]:
# TF(Term Frequencey) --> ek document m kisi word ka kitna contribution h
# IDF(Inverse Document Frequencey) --> 

In [17]:
# TF(t,d) = (Number of occurences of term t in document d) / (Total number of terms in the document d) 

# example ==>
# d1 = people watch cricket. 

# tf(people,d1) = 1/3 

# d2 = match was match. 
# tf(match , d2) = 2/3 

In [18]:
# IDF(t) = log(Total number of documents in the corpus) / (Number of documents with term t in them) 
# here corpus means the number of sentences

# Example ==>
# d1 = people watch cricket . 
# d2 = cricket was cricket . 
# d3 = people write comment .
# d4 = cricket write comment . 

# idf(cricket) = log(4/4)
# idf(people) = log(4/2) 

In [19]:
# we can use this by apply feature_extraction method in sklearn 

In [20]:
df

text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer  # text ko numbers me convert krega 


tfidf = TfidfVectorizer() 
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [22]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']


In [ ]:
# i love python 
# python is good
# python is useful

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer


df = pd.DataFrame({
    'text': [
        'i love python',
        'python is good',
        'python is useful'
    ],
    'output': [1, 0, 0]   
})

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df['text'])

print(vectorizer.get_feature_names_out())

print(X.toarray())

['good' 'is' 'love' 'python' 'useful']
[[0.         0.         0.861037   0.50854232 0.        ]
 [0.72033345 0.54783215 0.         0.42544054 0.        ]
 [0.         0.54783215 0.         0.42544054 0.72033345]]
